services:
  backend:
    build: ./back-end
    ports:
      - "5050:5050"
    restart: unless-stopped
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  frontend:
    build: ./front-end
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network
    logging:
      driver: "json-file"

networks:
  app-network:
    driver: bridge
