services:
  backend:
    build: ./back-end
    ports:
      - "5050:5050"
    restart: unless-stopped
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network

  frontend:
    build: ./front-end
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge