services:
  backend:
    build: ./back-end
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  frontend:
    build:
      context: ./front-end
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-certs:/etc/nginx/ssl:ro
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network
    logging:
      driver: "json-file"

networks:
  app-network:
    driver: bridge
