name: run backend test cases

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017

    defaults:
      run:
        working-directory: ./back-end

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: set up node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: install dependencies
      run: npm install

    - name: run tests with coverage
      env:
        JWT_SECRET: a-key-for-testing-lol
        MONGO_URI: mongodb://localhost:27017/nutrilens-test
        CI: true
      run: npx c8 mocha "test/**/*.test.js" --exit